// Copyright(c) 2016 - 2017 Federico Bolelli, Costantino Grana, Michele Cancilla, Lorenzo Baraldi and Roberto Vezzani
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met :
//
// *Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
//
// * Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation
// and / or other materials provided with the distribution.
//
// * Neither the name of YACCLAB nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED.IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

if (CONDITION_O) {
    if (CONDITION_N) {
        if (CONDITION_J) {
            if (CONDITION_I) {
                ACTION_6
            }
            else {
                if (CONDITION_C) {
                    if (CONDITION_H) {
                        ACTION_6
                    }
                    else {
                        if (CONDITION_G) {
                            if (CONDITION_B) {
                                ACTION_6
                            }
                            else {
                                ACTION_11
                            }
                        }
                        else {
                            ACTION_11
                        }
                    }
                }
                else {
                    ACTION_11
                }
            }
        }
        else {
            if (CONDITION_P) {
                if (CONDITION_K) {
                    if (CONDITION_D) {
                        if (CONDITION_I) {
                            ACTION_6
                        }
                        else {
                            if (CONDITION_C) {
                                if (CONDITION_H) {
                                    ACTION_6
                                }
                                else {
                                    if (CONDITION_G) {
                                        if (CONDITION_B) {
                                            ACTION_6
                                        }
                                        else {
                                            ACTION_12
                                        }
                                    }
                                    else {
                                        ACTION_12
                                    }
                                }
                            }
                            else {
                                ACTION_12
                            }
                        }
                    }
                    else {
                        ACTION_12
                    }
                }
                else {
                    ACTION_6
                }
            }
            else {
                ACTION_6
            }
        }
    }
    else {
        if (CONDITION_R) {
            if (CONDITION_J) {
                if (CONDITION_M) {
                    if (CONDITION_H) {
                        if (CONDITION_I) {
                            ACTION_6
                        }
                        else {
                            if (CONDITION_C) {
                                ACTION_6
                            }
                            else {
                                ACTION_11
                            }
                        }
                    }
                    else {
                        if (CONDITION_G) {
                            if (CONDITION_B) {
                                if (CONDITION_I) {
                                    ACTION_6
                                }
                                else {
                                    if (CONDITION_C) {
                                        ACTION_6
                                    }
                                    else {
                                        ACTION_11
                                    }
                                }
                            }
                            else {
                                ACTION_11
                            }
                        }
                        else {
                            ACTION_11
                        }
                    }
                }
                else {
                    if (CONDITION_I) {
                        ACTION_11
                    }
                    else {
                        if (CONDITION_H) {
                            if (CONDITION_C) {
                                ACTION_11
                            }
                            else {
                                ACTION_14
                            }
                        }
                        else {
                            ACTION_11
                        }
                    }
                }
            }
            else {
                if (CONDITION_P) {
                    if (CONDITION_K) {
                        if (CONDITION_M) {
                            if (CONDITION_H) {
                                if (CONDITION_D) {
                                    if (CONDITION_I) {
                                        ACTION_6
                                    }
                                    else {
                                        if (CONDITION_C) {
                                            ACTION_6
                                        }
                                        else {
                                            ACTION_12
                                        }
                                    }
                                }
                                else {
                                    ACTION_12
                                }
                            }
                            else {
                                if (CONDITION_D) {
                                    if (CONDITION_G) {
                                        if (CONDITION_B) {
                                            if (CONDITION_I) {
                                                ACTION_6
                                            }
                                            else {
                                                if (CONDITION_C) {
                                                    ACTION_6
                                                }
                                                else {
                                                    ACTION_12
                                                }
                                            }
                                        }
                                        else {
                                            ACTION_12
                                        }
                                    }
                                    else {
                                        ACTION_12
                                    }
                                }
                                else {
                                    if (CONDITION_I) {
                                        if (CONDITION_G) {
                                            if (CONDITION_B) {
                                                ACTION_12
                                            }
                                            else {
                                                ACTION_16
                                            }
                                        }
                                        else {
                                            ACTION_16
                                        }
                                    }
                                    else {
                                        ACTION_12
                                    }
                                }
                            }
                        }
                        else {
                            if (CONDITION_I) {
                                if (CONDITION_D) {
                                    ACTION_12
                                }
                                else {
                                    ACTION_16
                                }
                            }
                            else {
                                if (CONDITION_H) {
                                    if (CONDITION_D) {
                                        if (CONDITION_C) {
                                            ACTION_12
                                        }
                                        else {
                                            ACTION_15
                                        }
                                    }
                                    else {
                                        ACTION_15
                                    }
                                }
                                else {
                                    ACTION_12
                                }
                            }
                        }
                    }
                    else {
                        if (CONDITION_H) {
                            if (CONDITION_M) {
                                ACTION_6
                            }
                            else {
                                ACTION_9
                            }
                        }
                        else {
                            if (CONDITION_I) {
                                if (CONDITION_M) {
                                    if (CONDITION_G) {
                                        if (CONDITION_B) {
                                            ACTION_6
                                        }
                                        else {
                                            ACTION_11
                                        }
                                    }
                                    else {
                                        ACTION_11
                                    }
                                }
                                else {
                                    ACTION_11
                                }
                            }
                            else {
                                ACTION_6
                            }
                        }
                    }
                }
                else {
                    if (CONDITION_H) {
                        if (CONDITION_M) {
                            ACTION_6
                        }
                        else {
                            ACTION_9
                        }
                    }
                    else {
                        if (CONDITION_I) {
                            if (CONDITION_M) {
                                if (CONDITION_G) {
                                    if (CONDITION_B) {
                                        ACTION_6
                                    }
                                    else {
                                        ACTION_11
                                    }
                                }
                                else {
                                    ACTION_11
                                }
                            }
                            else {
                                ACTION_11
                            }
                        }
                        else {
                            ACTION_6
                        }
                    }
                }
            }
        }
        else {
            if (CONDITION_J) {
                if (CONDITION_I) {
                    ACTION_4
                }
                else {
                    if (CONDITION_H) {
                        if (CONDITION_C) {
                            ACTION_4
                        }
                        else {
                            ACTION_7
                        }
                    }
                    else {
                        ACTION_4
                    }
                }
            }
            else {
                if (CONDITION_P) {
                    if (CONDITION_K) {
                        if (CONDITION_I) {
                            if (CONDITION_D) {
                                ACTION_5
                            }
                            else {
                                ACTION_10
                            }
                        }
                        else {
                            if (CONDITION_H) {
                                if (CONDITION_D) {
                                    if (CONDITION_C) {
                                        ACTION_5
                                    }
                                    else {
                                        ACTION_8
                                    }
                                }
                                else {
                                    ACTION_8
                                }
                            }
                            else {
                                ACTION_5
                            }
                        }
                    }
                    else {
                        if (CONDITION_I) {
                            ACTION_4
                        }
                        else {
                            if (CONDITION_H) {
                                ACTION_3
                            }
                            else {
                                ACTION_2
                            }
                        }
                    }
                }
                else {
                    if (CONDITION_I) {
                        ACTION_4
                    }
                    else {
                        if (CONDITION_H) {
                            ACTION_3
                        }
                        else {
                            ACTION_2
                        }
                    }
                }
            }
        }
    }
}
else {
    if (CONDITION_S) {
        if (CONDITION_P) {
            if (CONDITION_N) {
                if (CONDITION_J) {
                    if (CONDITION_I) {
                        ACTION_6
                    }
                    else {
                        if (CONDITION_C) {
                            if (CONDITION_H) {
                                ACTION_6
                            }
                            else {
                                if (CONDITION_G) {
                                    if (CONDITION_B) {
                                        ACTION_6
                                    }
                                    else {
                                        ACTION_11
                                    }
                                }
                                else {
                                    ACTION_11
                                }
                            }
                        }
                        else {
                            ACTION_11
                        }
                    }
                }
                else {
                    if (CONDITION_K) {
                        if (CONDITION_D) {
                            if (CONDITION_I) {
                                ACTION_6
                            }
                            else {
                                if (CONDITION_C) {
                                    if (CONDITION_H) {
                                        ACTION_6
                                    }
                                    else {
                                        if (CONDITION_G) {
                                            if (CONDITION_B) {
                                                ACTION_6
                                            }
                                            else {
                                                ACTION_12
                                            }
                                        }
                                        else {
                                            ACTION_12
                                        }
                                    }
                                }
                                else {
                                    ACTION_12
                                }
                            }
                        }
                        else {
                            ACTION_12
                        }
                    }
                    else {
                        ACTION_6
                    }
                }
            }
            else {
                if (CONDITION_R) {
                    if (CONDITION_J) {
                        if (CONDITION_M) {
                            if (CONDITION_H) {
                                if (CONDITION_I) {
                                    ACTION_6
                                }
                                else {
                                    if (CONDITION_C) {
                                        ACTION_6
                                    }
                                    else {
                                        ACTION_11
                                    }
                                }
                            }
                            else {
                                if (CONDITION_G) {
                                    if (CONDITION_B) {
                                        if (CONDITION_I) {
                                            ACTION_6
                                        }
                                        else {
                                            if (CONDITION_C) {
                                                ACTION_6
                                            }
                                            else {
                                                ACTION_11
                                            }
                                        }
                                    }
                                    else {
                                        ACTION_11
                                    }
                                }
                                else {
                                    ACTION_11
                                }
                            }
                        }
                        else {
                            ACTION_11
                        }
                    }
                    else {
                        if (CONDITION_K) {
                            if (CONDITION_D) {
                                if (CONDITION_M) {
                                    if (CONDITION_H) {
                                        if (CONDITION_I) {
                                            ACTION_6
                                        }
                                        else {
                                            if (CONDITION_C) {
                                                ACTION_6
                                            }
                                            else {
                                                ACTION_12
                                            }
                                        }
                                    }
                                    else {
                                        if (CONDITION_G) {
                                            if (CONDITION_B) {
                                                if (CONDITION_I) {
                                                    ACTION_6
                                                }
                                                else {
                                                    if (CONDITION_C) {
                                                        ACTION_6
                                                    }
                                                    else {
                                                        ACTION_12
                                                    }
                                                }
                                            }
                                            else {
                                                ACTION_12
                                            }
                                        }
                                        else {
                                            ACTION_12
                                        }
                                    }
                                }
                                else {
                                    ACTION_12
                                }
                            }
                            else {
                                if (CONDITION_I) {
                                    if (CONDITION_M) {
                                        if (CONDITION_H) {
                                            ACTION_12
                                        }
                                        else {
                                            if (CONDITION_G) {
                                                if (CONDITION_B) {
                                                    ACTION_12
                                                }
                                                else {
                                                    ACTION_16
                                                }
                                            }
                                            else {
                                                ACTION_16
                                            }
                                        }
                                    }
                                    else {
                                        ACTION_16
                                    }
                                }
                                else {
                                    ACTION_12
                                }
                            }
                        }
                        else {
                            if (CONDITION_I) {
                                if (CONDITION_M) {
                                    if (CONDITION_H) {
                                        ACTION_6
                                    }
                                    else {
                                        if (CONDITION_G) {
                                            if (CONDITION_B) {
                                                ACTION_6
                                            }
                                            else {
                                                ACTION_11
                                            }
                                        }
                                        else {
                                            ACTION_11
                                        }
                                    }
                                }
                                else {
                                    ACTION_11
                                }
                            }
                            else {
                                ACTION_6
                            }
                        }
                    }
                }
                else {
                    if (CONDITION_J) {
                        ACTION_4
                    }
                    else {
                        if (CONDITION_K) {
                            if (CONDITION_I) {
                                if (CONDITION_D) {
                                    ACTION_5
                                }
                                else {
                                    ACTION_10
                                }
                            }
                            else {
                                ACTION_5
                            }
                        }
                        else {
                            if (CONDITION_I) {
                                ACTION_4
                            }
                            else {
                                ACTION_2
                            }
                        }
                    }
                }
            }
        }
        else {
            if (CONDITION_R) {
                ACTION_6
            }
            else {
                if (CONDITION_N) {
                    ACTION_6
                }
                else {
                    ACTION_2
                }
            }
        }
    }
    else {
        if (CONDITION_P) {
            if (CONDITION_J) {
                ACTION_4
            }
            else {
                if (CONDITION_K) {
                    if (CONDITION_I) {
                        if (CONDITION_D) {
                            ACTION_5
                        }
                        else {
                            ACTION_10
                        }
                    }
                    else {
                        ACTION_5
                    }
                }
                else {
                    if (CONDITION_I) {
                        ACTION_4
                    }
                    else {
                        ACTION_2
                    }
                }
            }
        }
        else {
            if (CONDITION_T) {
                ACTION_2
            }
            else {
                ACTION_1
            }
        }
    }
}