

			if (CONDITION_O) {
				if (CONDITION_H) {
					ACTION_NW
				}
				else {
					if (CONDITION_I || CONDITION_J) {
						ACTION_N
					}
					else {
						if (CONDITION_P && CONDITION_K) {
							ACTION_NE
						}
						else {
							if (CONDITION_N || CONDITION_R) {
								ACTION_W
							}
							else {
								ACTION_C
							}
						}
					}
				}
			}
			else {
				if (CONDITION_P) {
					if (CONDITION_I || CONDITION_J) {
						ACTION_N
					}
					else {
						if (CONDITION_K) {
							ACTION_NE
						}
						else {
							if (CONDITION_S && (CONDITION_N || CONDITION_R)) {
								ACTION_W
							}
							else {
								ACTION_C
							}
						}
					}
				}
				else {
					if (CONDITION_S) {
						if (CONDITION_N && CONDITION_R) {
							ACTION_W
						}
						else {
							ACTION_C
						}
					}
					else {
						if (CONDITION_T) {
							ACTION_C
						}
						else {
							ACTION_C
						}
					}
				}
			}